language: node_js
env:
    global: github.com/sixertoy/include.git
branches:
  only:
    - master
node_js:
  - "4.4.1"
before_install:
  - npm install -g gulp-cli eslint istanbul coveralls
script:
  - npm test --verbose
after_success:
  - cat ./coverage/lcov.info | coveralls && rm -rf ./coverage
  
